version: '3'
services:
  php:
    build: ./php
    volumes: 
      - ./html:/var/www/html
      - ./php/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80" 
    depends_on: 
      - db

  db:
    image: mysql:5.7
    ports: 
      - 3306:3306
    volumes: 
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
     - 8080:80
    environment:
     - PMA_PASSWORD=password
    depends_on:
      - db
    volumes:
      - ./phpmyadmin/sessions:/sessions